---
name: "notify_yetibot"
enabled: true
description: "Notification rule to send messages to Yetibot"
trigger:
  type: "core.st2.generic.notifytrigger"
criteria:
  trigger.route:
    pattern: "yetibot"
    type: "equals"
action:
  ref: core.http
  parameters:
    method: POST
    body: "command=echo%20{{trigger.message}}%20{{trigger.data.result|urlencode}}&chat-source={{trigger.data.source_channel|urlencode}}"
    url: "{{system.yetibot_endpoint}}/api"
